import type { HabitTemplate } from '@/domain/entities/template';

/** 首次引導用的內建範本（無 SyncBase，不進 Dexie，純靜態資料）。 */
export const ONBOARDING_TEMPLATES: HabitTemplate[] = [
  {
    id: 'tpl-water',
    name: '喝水',
    emoji: '💧',
    color: '#06b6d4',
    type: 'count',
    unit: '杯',
    decimal: false,
    step: 1,
    goalDaily: 8,
    tags: [],
  },
  {
    id: 'tpl-exercise',
    name: '運動',
    emoji: '🏃',
    color: '#ef4444',
    type: 'timer',
    unit: '分鐘',
    decimal: false,
    step: 5,
    goalDaily: 30,
    tags: [],
  },
  {
    id: 'tpl-reading',
    name: '閱讀',
    emoji: '📖',
    color: '#8b5cf6',
    type: 'timer',
    unit: '分鐘',
    decimal: false,
    step: 10,
    goalDaily: 20,
    tags: [],
  },
  {
    id: 'tpl-meditation',
    name: '冥想',
    emoji: '🧘',
    color: '#6366f1',
    type: 'timer',
    unit: '分鐘',
    decimal: false,
    step: 5,
    goalDaily: 10,
    tags: [],
  },
  {
    id: 'tpl-sleep',
    name: '早睡',
    emoji: '😴',
    color: '#64748b',
    type: 'check',
    decimal: false,
    step: 1,
    tags: [],
  },
  {
    id: 'tpl-diet',
    name: '健康飲食',
    emoji: '🥗',
    color: '#22c55e',
    type: 'check',
    decimal: false,
    step: 1,
    tags: [],
  },
  {
    id: 'tpl-walk',
    name: '走路',
    emoji: '🚶',
    color: '#f59e0b',
    type: 'count',
    unit: '公里',
    decimal: true,
    step: 1,
    goalDaily: 3,
    tags: [],
  },
  {
    id: 'tpl-journal',
    name: '寫日記',
    emoji: '✍️',
    color: '#ec4899',
    type: 'check',
    decimal: false,
    step: 1,
    tags: [],
  },
];
